#!/bin/bash
# This script is executed within a Docker container

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin
export GOPATH=/home/linuxboot/mainboards/$BOARDS
if [ "$PROXY" != "" ]
then
git config --global https.proxy $PROXY
git config --global http.proxy $PROXY
git config --global url.https://github.com/.insteadOf git://github.com/
fi
if [ "$GITTOKEN" != "OSFCIemptyOSFCI" ]
then
	newRepo=`echo $GITHUBREPO | sed "s/:\/\//:\/\/$GITTOKEN\@/"`
	export GITHUBREPO=$newRepo
fi
git clone $GITHUBREPO
cd mainboards
git checkout -b $BRANCH origin/$BRANCH
cd $BOARDS
export GO111MODULE=off
make fetch
go build github.com/u-root/u-root
export PATH=$PATH:.:./bin
export PATH=/home/linuxboot/mainboards/hpe/dl360gen10/bin/u-root:$PATH
cp /volume/default.rom ROM.bin
# export KEYPATH=""
# if [ -f "/volume/id_rsa.pub" ]
# then
# export KEYPATH=/volume/id_rsa.pub
# fi
make image.bin
cp image.bin /volume/linuxboot.rom
