#!/bin/bash
# This script is executed within a Docker container

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/local/go/bin
export GOPATH=:/go/src/base:/home/linuxboot/mainboards/$BOARDS
git clone $GITHUBREPO
cd mainboards
git checkout $BRANCH
cd $BOARDS
make fetch
go build github.com/u-root/u-root
export PATH=$PATH:.
make uroot
make bzImage
cp ./linux/arch/x86/boot/bzImage linuxboot.bin
cp linuxboot.bin /volume
