#!/bin/bash
# This script is executed within a Docker container

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
echo "proxy in use: $PROXY"

if [ "$PROXY" != "" ]
then
git config --global https.proxy $PROXY
git config --global http.proxy $PROXY
git config --global url.https://github.com/.insteadOf git://github.com/
npm config set proxy $PROXY
npm config set https-proxy $PROXY
export http_proxy=$PROXY
export https_proxy=$PROXY
fi

if [ "$GITTOKEN" != "OSFCIemptyOSFCI" ]
then
	git config --global github.token $GITTOKEN
        newRepo=`echo $GITHUBREPO | sed "s/:\/\//:\/\/$GITTOKEN\@/"`
        export GITHUBREPO=$newRepo
fi
git clone $GITHUBREPO
OPENBMCDIR=$(basename -s .git $GITHUBREPO)
cd $OPENBMCDIR
git checkout -b $BRANCH origin/$BRANCH
export SSTATE_DIR=/datas/SSTATE
. ./setup $RECIPES
echo "SSTATE_DIR ?= \"/datas/SSTATE\"" >> conf/local.conf
echo "DL_DIR ?= \"/datas/dl\"" >> conf/local.conf
if [ "$INTERACTIVE" != "0" ]
then
bitbake obmc-phosphor-image
else
bitbake -v obmc-phosphor-image
fi
cp tmp/deploy/images/$RECIPES/obmc-phosphor-image-$RECIPES-*.static.mtd /volume/obmc-$RECIPES.static.mtd
