#!/bin/bash
if [ ! -d $1/bin ]
then
mkdir $1/bin
fi
if [ ! -d $1/tmp ]
then
mkdir $1/tmp
mkfifo $1/tmp/bios_fifo
fi
if [ ! -d $1/docker ]
then
mkdir $1/docker
fi
if [ ! -d $1/images ]
then
mkdir $1/images
fi
cp startLinuxbootBuild $1/bin
cp startLinuxbootBuildWrapper $1/bin
chmod -Rf 777 $1/bin
cp -Rf Docker* $1/docker
cp build_linuxboot $1/docker
docker image rm linuxboot
docker build -t linuxboot -f $1/docker/Dockerfile.linuxboot $1/docker/
basePath=`realpath ..`
export GOPATH=$GOPATH:$basePath
go get golang.org/x/crypto/bcrypt
go build compile.go
cp compile $1/bin
# We need UTK from fiano project
git clone https://github.com/linuxboot/fiano
cd fiano/cmds/utk
go get go get github.com/linuxboot/fiano/pkg/utk
go build utk.go
cp utk $1/bin
cd ../../..
cp ./readBiosFifo $1/bin
mkdir /tmp/ttyd
cp ../ctrl/ttyd/ttyd.tar.gz /tmp/ttyd
cd /tmp/ttyd
gunzip ttyd.tar.gz
tar xf ttyd.tar
cd ttyd
mkdir build
cd build
cmake ..
make
cp ttyd $1/bin

