#!/bin/bash
export USER=$1
function exitWrapper()
{
        docker container kill linuxboot_$USER
        kill -SIGINT $ttydPID
	active_screen=`screen -ls | grep pts | cut -d. -f1 | awk '{print $1}'`
	for i in $active_screen
	do
		launcher=`cat /proc/$i/cmdline | tr '\000' ' ' | awk '{print $2}'`
		if [ "$launcher" == "$BINARIES_PATH/startLinuxbootBuild" ]
		then
			kill -9 $i
		fi
	done
#        screen -ls | grep pts | cut -d. -f1 | awk '{print $1}' | xargs kill
        exit 0
}
trap exitWrapper SIGINT
$BINARIES_PATH/ttyd -p 7681 -s 9 screen $BINARIES_PATH/startLinuxbootBuild "$@"  &
ttydPID=$!
while true
do
        sleep 1
done

# ( $BINARIES_PATH/startLinuxbootBuild "$@" ) >& $PIPE_PATH/bios_fifo
