#!/bin/bash
ttydPID="-2"
SUM=`md5sum <<EOF
$1
EOF`
SUM=`echo $SUM | awk '{ print $1 }'`
function exitWrapper()
{
	docker container kill openbmc_$SUM
	if [ "$ttydPID" != "-2" ]
	then
		kill -SIGINT $ttydPID
	fi
        active_screen=`screen -ls | grep pts | cut -d. -f1 | awk '{print $1}'`
        for i in $active_screen
        do
                launcher=`cat /proc/$i/cmdline | tr '\000' ' ' | awk '{print $5}'`
                if [ "$launcher" == "$BINARIES_PATH/startOpenBMCBuild" ]
                then
                        kill -9 $i
                fi
        done
	exit 0
}
trap exitWrapper SIGINT
if [ "$7" == "1" ]
then
$BINARIES_PATH/ttyd -p 7682 -s 9 screen -L -Logfile /tmp/openbmc_$1 $BINARIES_PATH/startOpenBMCBuild "$@"  &
ttydPID=$!
else
screen -d -m -L -Logfile /tmp/linuxboot_$1 $BINARIES_PATH/startOpenBMCBuild "$@"  &
ttydPID="-2"
fi
if [ "$7" == "1" ]
then
	while true
	do
		sleep 1
	done
fi
