#!/bin/bash
USERNAME=$1
GITHUBREPO=$2
BRANCH=$3
RECIPES=$4
PROXY=$5
echo $RECIPES
if [ ! -d /tmp/volume/$USERNAME ]
then
mkdir /tmp/volume/$USERNAME
else
rm /tmp/volume/$USERNAME/*
fi
docker run --name openbmc_$USERNAME -v /datas:/datas -v /tmp/volume/$USERNAME:/volume -e RECIPES=$RECIPES -e GITHUBREPO=$GITHUBREPO -e BRANCH=$BRANCH -e PROXY=$PROXY --rm=true  -t openbmc
if [ -f /tmp/volume/$USERNAME/obmc-dl360poc.static.mtd ]
then
\rm $FIRMWARES_PATH/test_openbmc_$USERNAME.mtd
cp /tmp/volume/$USERNAME/obmc-dl360poc.static.mtd $FIRMWARES_PATH/test_openbmc_$USERNAME.mtd
echo "Image successfully generated ..."
echo "DONE !"
while true
do
sleep 60
done
fi
