#!/bin/bash
SUM=`md5sum <<EOF
$1
EOF`
SUM=`echo $SUM | awk '{ print $1 }'`
function exitWrapper()
{
	docker container kill openbmc_$SUM
	kill -SIGINT $ttydPID
        for i in $active_screen
        do
                launcher=`cat /proc/$i/cmdline | tr '\000' ' ' | awk '{print $2}'`
                if [ "$launcher" == "$BINARIES_PATH/startOpenBMCBuild" ]
                then
                        kill -9 $i
                fi
        done
#	screen -ls | grep pts | cut -d. -f1 | awk '{print $1}' | xargs kill
	exit 0
}
trap exitWrapper SIGINT
$BINARIES_PATH/ttyd -p 7682 -s 9 screen $BINARIES_PATH/startOpenBMCBuild "$@"  &
ttydPID=$!
while true
do
	sleep 1
done
