#!/bin/bash
USERNAME=$1
GITHUBREPO=$2
BRANCH=$3
RECIPES=$4
STORAGE_URI=$5
STORAGE_TCPPORT=$6
INTERACTIVE=$7
PROXY=$8
SUM=`md5sum <<EOF
$USERNAME
EOF`
SUM=`echo $SUM | awk '{ print $1 }'`
if [ ! -d /tmp/volume/openbmc_$USERNAME ]
then
mkdir /tmp/volume/openbmc_$USERNAME
else
rm -rf /tmp/volume/openbmc_$USERNAME/*
fi
docker run -d --name openbmc_$SUM -v /datas:/datas -v /tmp/volume/openbmc_$USERNAME:/volume -e RECIPES=$RECIPES -e GITHUBREPO=$GITHUBREPO -e BRANCH=$BRANCH -e PROXY=$PROXY -e INTERACTIVE=$INTERACTIVE --rm=true  -t openbmc
docker logs -f openbmc_$SUM
docker wait openbmc_$SUM
if [ -f /tmp/volume/openbmc_$USERNAME/obmc-dl360poc.static.mtd ]
then
\rm $FIRMWARES_PATH/test_openbmc_$USERNAME.mtd
cp /tmp/volume/openbmc_$USERNAME/obmc-dl360poc.static.mtd $FIRMWARES_PATH/test_openbmc_$USERNAME.mtd
echo "Image successfully generated ..."
echo "DONE !"
curl -H "Content-Type:application/octet-stream" -T $FIRMWARES_PATH/test_openbmc_$USERNAME.mtd http://$STORAGE_URI$STORAGE_TCPPORT/user/$USERNAME/openbmc/test_$USERNAME.rom
fi
if [ "$INTERACTIVE" == "1" ]
then
	while true
	do
		sleep 60
	done
fi
