#!/bin/bash
export LD_LIBRARY_PATH=$OLD_LIBRARIES
$BINARIES_PATH/iPDU $1
if [ "$1" == "on" ]
then
# We switch the Acroname to the host
$BINARIES_PATH/switch
fi
if [ "$1" == "off" ]
then
echo "Running cleanup" >/tmp/cleanup
$BINARIES_PATH/cleanUP
fi
