#!/bin/bash
BINARIES_PATH=$(grep -A0 'BINARIES_PATH' "/usr/local/production/config/ctrl1conf.yaml" | cut -d: -f2 | sed 's/[\" ]//g')
LD_LIBRARY_PATH=$(grep -A0 'OLD_LIBRARIES' "/usr/local/production/config/ctrl1conf.yaml" | cut -d: -f2 | sed 's/[\" ]//g')
$BINARIES_PATH/iPDU $1
if [ "$1" == "on" ]
then
# We switch the Acroname to the host
$BINARIES_PATH/switch
fi
