#!/bin/bash
# (c) 2020 Hewlett-Packard LP.



#Gregg 1/4/2024 - I am taking all this code out, it is not needed anymore.  No detection necessary to find the emulators, we will just turn off ports 1/2 on the hub



BINARIES_PATH=$(grep -A0 'BINARIES_PATH' "/usr/local/production/config/ctrl1conf.yaml" | cut -d: -f2 | sed 's/[\" ]//g')
EM100BMC=$(grep -A0 'EM100BMC' "/usr/local/production/config/ctrl1conf.yaml" | cut -d: -f2 | sed 's/[\" ]//g')
EM100BIOS=$(grep -A0 'EM100BIOS' "/usr/local/production/config/ctrl1conf.yaml" | cut -d: -f2 | sed 's/[\" ]//g')


<<'END_COMMENT'

EM100BMC=$(grep -A0 'EM100BMC' "/usr/local/production/config/ctrl1conf.yaml" | cut -d: -f2 | sed 's/[\" ]//g')
EM100BIOS=$(grep -A0 'EM100BIOS' "/usr/local/production/config/ctrl1conf.yaml" | cut -d: -f2 | sed 's/[\" ]//g')
echo "reset" >> $BINARIES_PATH/.emulators/out
DEVICE=
if [ "$1" == "bmc" ]
then
DEVICE=`echo $EM100BMC`
fi
if [ "$1" == "rom" ]
then
DEVICE=$EM100BIOS
fi
echo "$DEVICE" >> $BINARIES_PATH/.emulators/out
if [ "$DEVICE" == "" ]
then
exit 0
fi
echo $DEVICE
DEVICEID=`cat $BINARIES_PATH/.emulators/config_em100.txt | grep $DEVICE | awk '{ print $4}' | sed 's/://' | bc`
echo $DEVICEID
# We need to find the HUB ID and the PORT ID from the USB config tree
IFS=$'\n'
usbtree=`cat $BINARIES_PATH/.emulators/config_usb_tree.txt`
currenthub=""
for i in ${usbtree[@]}
do
        isroothub=`echo $i | grep "Class=root_hub"`
        if [ "$isroothub" != "" ]
        then
                BUS=`echo $isroothub | awk '{ print $3}' | awk -F"." '{ print $1 }' | bc`
        fi
        ishub=`echo $i | grep "Class=Hub"`
        if [ "$ishub" != "" ]
        then
                currentport=`echo $ishub | awk '{ print $3 }' | sed 's/://'`
                currentdev=`echo $ishub | awk '{ print $5 }' | sed 's/,//'`
                currenthub="$BUS-$currentport"
                echo "CURRENT HUB $currenthub" >> out
        fi
        ismyport=`echo $i | grep "Dev $DEVICEID"`
        if [ "$ismyport" != "" ]
        then
                PORTID=`echo $i | grep "Dev $DEVICEID" | awk '{ print $3 }' | sed 's/://'`
                HUB="$currenthub"
                break
        fi
done
unset IFS
echo "RESETTING hub $HUB port $PORTID"  >> $BINARIES_PATH/.emulators/out
echo $HUB
echo $PORTID

END_COMMENT

port=1
hub=$($BINARIES_PATH/cusbi /Q:ttyUSB$port -F)
echo $hub
echo $port
if [ "$hub" == "Query Err" ]
then
        port=0
fi

if [ "$1" == "bmc" ]
then
        $BINARIES_PATH/cusbi /S:ttyUSB$port 0:1
        sleep 5s
        $BINARIES_PATH/cusbi /S:ttyUSB$port 1:1
        sleep 5s
        exit 0
elif [ "$1" == "rom" ]
then
	$BINARIES_PATH/cusbi /S:ttyUSB$port 0:2
        sleep 5s
        $BINARIES_PATH/cusbi /S:ttyUSB$port 1:2
        sleep 5s
        exit 0

else 
	$BINARIES_PATH/cusbi /S:ttyUSB$port 0:1,2
	sleep 5s
	$BINARIES_PATH/cusbi /S:ttyUSB$port 1:1,2
	sleep 5s
	exit 0
fi

#echo "done" >> $BINARIES_PATH/.emulators/out
#( $BINARIES_PATH/em100 -l ) >& $BINARIES_PATH/.emulators/config_em100.txt
#( cat $BINARIES_PATH/.emulators/config_em100.txt | sed 's/EM/DP/g'  ) >& $BINARIES_PATH/.emulators/config_em100.txt.n
#mv $BINARIES_PATH/.emulators/config_em100.txt.n $BINARIES_PATH/.emulators/config_em100.txt
#( lsusb -t ) >& $BINARIES_PATH/.emulators/config_usb_tree.txt
	


#$BINARIES_PATH/uhubctl -l $HUB -p $PORTID -a off
#$BINARIES_PATH/cusbi /S:ttyUSB$port 0:1,2
#/usr/local/production/bin/cusbi /S:ttyUSB$port 0:1,2
#$BINARIES_PATH/cusbi /Q:ttyUSB$port 
#sleep 5s
#$BINARIES_PATH/uhubctl -l $HUB -p $PORTID -a on
#$BINARIES_PATH/cusbi /S:ttyUSB$port 1:1,2
#/usr/local/production/bin/cusbi /S:ttyUSB$port 1:1,2
#$BINARIES_PATH/cusbi /Q:ttyUSB$port 
#sleep 5s
#echo "Is this 5 seconds"
#echo "done" >> $BINARIES_PATH/.emulators/out
#( $BINARIES_PATH/em100 -l ) >& $BINARIES_PATH/.emulators/config_em100.txt
#( cat $BINARIES_PATH/.emulators/config_em100.txt | sed 's/EM/DP/g'  ) >& $BINARIES_PATH/.emulators/config_em100.txt.n
#mv $BINARIES_PATH/.emulators/config_em100.txt.n $BINARIES_PATH/.emulators/config_em100.txt
#( lsusb -t ) >& $BINARIES_PATH/.emulators/config_usb_tree.txt
#exit 0
