#!/bin/bash
cp /usr/share/local/images/ilo_dl360_OpenBMC.rom firmwares
$HOME/build/ttyd/ttyd -p 7681 -R $HOME/Web/read_pipe &
$HOME/build/ttyd/ttyd -p 7682 screen /dev/ttyUSB0 115200  &
( unbuffer em100 -c MX25L25635E -x DP144197 -d $1 -r -t -v  -O 0xFE0000000 -p low ) >& iloem100
sleep 2
