#!/bin/bash
cp $ORIGINAL_BIOS $FIRMWARES_PATH
$HOME/build/ttyd/ttyd -p 7683 -R $BINARIES_PATH/read_pipe_smbios &
( unbuffer em100 -c MX25L51245G -x DP144198 -d $1 -r -t -v  -O 0xFE0000000 -p low ) >& $PIPE_PATH/smbiosem100
sleep 2
